export const ALL_COURSES = [
  {
    id: 'yellow-belt',
    title: 'Lean Six Sigma Yellow Belt',
    level: 'Entry Level',
    duration: '2 Weeks',
    mode: ['Online', 'Onsite'],
    accreditation: ['CSSC'],
    idealFor: 'Team members, Entry-level professionals, Process participants',
    outcome: 'CSSC Certified Yellow Belt - Foundation in process improvement and quality tools',
    certification: 'Lean Six Sigma Yellow Belt Certification by CSSC',
    description:
      'Perfect introduction to Lean Six Sigma methodologies. Learn fundamental problem-solving tools and support improvement projects.',
    topics: [
      'DMAIC Framework',
      'Basic Statistics',
      'Process Mapping',
      'Root Cause Analysis',
      'Waste Identification',
    ],
    price: '₹15,000',
  },
  {
    id: 'green-belt',
    title: 'Lean Six Sigma Green Belt',
    level: 'Intermediate',
    duration: '4 Weeks',
    mode: ['Online', 'Onsite', 'Hybrid'],
    accreditation: ['CSSC', 'IAF'],
    idealFor: 'Project leaders, Quality analysts, Process improvement professionals',
    outcome: 'CSSC & IAF Certified Green Belt - Lead small to medium improvement projects',
    certification: 'Dual Certification: CSSC Green Belt + IAF Accredited Certificate',
    description:
      'Master the fundamentals of process improvement and lead small to medium-scale projects with confidence.',
    topics: [
      'Advanced DMAIC',
      'Statistical Analysis',
      'Hypothesis Testing',
      'Control Charts',
      'Project Management',
    ],
    price: '₹35,000',
  },
  {
    id: 'black-belt',
    title: 'Lean Six Sigma Black Belt',
    level: 'Advanced',
    duration: '6 Weeks',
    mode: ['Online', 'Hybrid'],
    accreditation: ['CSSC', 'IAF'],
    idealFor: 'Senior analysts, Department heads, Improvement champions',
    outcome: 'CSSC & IAF Certified Black Belt - Drive complex projects and mentor Green Belts',
    certification: 'Dual Certification: CSSC Black Belt + IAF Accredited Master Certificate',
    description:
      'Advanced training for leading complex improvement projects and mentoring Green Belts in your organization.',
    topics: [
      'Advanced Statistics',
      'Design of Experiments',
      'Regression Analysis',
      'Team Leadership',
      'Change Management',
    ],
    price: '₹75,000',
  },
  {
    id: 'master-black-belt',
    title: 'Lean Six Sigma Master Black Belt',
    level: 'Expert',
    duration: '8 Weeks',
    mode: ['Hybrid'],
    accreditation: ['CSSC', 'IAF'],
    idealFor: 'Executives, Program directors, Organizational leaders',
    outcome:
      'CSSC & IAF Certified Master Black Belt - Strategic leadership in organizational excellence',
    certification: 'Elite Dual Certification: CSSC Master Black Belt + IAF Excellence Award',
    description:
      'Elite certification for strategic leaders driving organizational excellence and mentoring Black Belts.',
    topics: [
      'Strategic Deployment',
      'Advanced Analytics',
      'Organizational Design',
      'Executive Coaching',
      'Program Management',
    ],
    price: '₹1,50,000',
  },
  {
    id: 'lean-practitioner',
    title: 'Lean Practitioner',
    level: 'Specialized',
    duration: '3 Weeks',
    mode: ['Online', 'Onsite'],
    accreditation: ['CSSC'],
    idealFor: 'Operations managers, Manufacturing professionals, Supply chain specialists',
    outcome: 'CSSC Certified Lean Practitioner - Implement Lean principles across operations',
    certification: 'CSSC Lean Practitioner Certificate with Value Stream Mapping Specialization',
    description:
      'Specialized training in Lean principles, waste elimination, and continuous flow improvement for operational excellence.',
    topics: [
      'Value Stream Mapping',
      '5S Implementation',
      'Kanban Systems',
      'Pull Production',
      'Kaizen Events',
    ],
    price: '₹28,000',
  },
]

export const COMPARISON_HEADERS = [
  'Course',
  'Duration',
  'Mode',
  'Accreditation',
  'Ideal For',
  'Outcome',
]
